In [179]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
from pandas.plotting import scatter_matrix
pd.set_option('display.max_columns', None)

import numpy as np
np.set_printoptions(linewidth=10000, precision=3)

import re
from google.cloud import storage

import duckdb

In [180]:
# client = storage.Client()
# blobs = client.list_blobs('nrl-data-dev')

# dfs = []
# for blob in blobs:
#     print(blob.name) # rather use tqdm
#     match = re.search(r"nrl/match_data/(\d{4})_r(\d+)\.json", blob.name)
#     df = pd.read_json(f'gs://nrl-data-dev/{blob.name}')
#     df['year'] = int(match.group(1))
#     df['round_num'] = int(match.group(2))
#     dfs.append(df)
# df = pd.concat(dfs, axis=0, ignore_index=True)
# df.to_csv('match_data_temp.csv', index=False)

df = pd.read_csv('match_data_temp.csv')
df

,Round,Home,Home_Score,Away,Away_Score,Venue,Date,Match_Centre_URL,year,round_num
0,Round 1,Rams,8,Cowboys,18,Adelaide Oval,1998-03-13 00:00:00+00:00,https://www.nrl.com/draw/nrl-premiership/1998/...,1998,1
1,Round 1,Broncos,22,Sea Eagles,6,Queensland Sport and Athletics Centre,1998-03-13 00:00:00+00:00,https://www.nrl.com/draw/nrl-premiership/1998/...,1998,1
2,Round 1,Warriors,18,Rabbitohs,24,Go Media Stadium,1998-03-13 00:00:00+00:00,https://www.nrl.com/draw/nrl-premiership/1998/...,1998,1
3,Round 1,Tigers,40,Chargers,6,Leichhardt Oval,1998-03-14 00:00:00+00:00,https://www.nrl.com/draw/nrl-premiership/1998/...,1998,1
4,Round 1,Eels,27,Panthers,16,CommBank Stadium,1998-03-14 00:00:00+00:00,https://www.nrl.com/draw/nrl-premiership/1998/...,1998,1
...,...,...,...,...,...,...,...,...,...,...
5562,Round 9,Warriors,30,Cowboys,26,Suncorp Stadium,2025-05-03 07:30:00+00:00,https://www.nrl.com/draw/nrl-premiership/2025/...,2025,9
5563,Round 9,Wests Tigers,34,Dragons,28,Suncorp Stadium,2025-05-03 09:45:00+00:00,https://www.nrl.com/draw/nrl-premiership/2025/...,2025,9
5564,Round 9,Titans,18,Bulldogs,38,Suncorp Stadium,2025-05-04 03:50:00+00:00,https://www.nrl.com/draw/nrl-premiership/2025/...,2025,9
5565,Round 9,Panthers,32,Broncos,8,Suncorp Stadium,2025-05-04 06:05:00+00:00,https://www.nrl.com/draw/nrl-premiership/2025/...,2025,9
5566,Round 9,Storm,18,Raiders,20,Suncorp Stadium,2025-05-04 08:25:00+00:00,https://www.nrl.com/draw/nrl-premiership/2025/...,2025,9

In [181]:
df.groupby('year').round_num.value_counts().unstack()

round_num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1998,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0
1999,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2000,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2001,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2002,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2003,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2004,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2005,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2006,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2007,8.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2008,8.0,8.0,8.0,8.0,8.0,8.0,6.0,5.0,6.0,8.0,5.0,8.0,8.0,5.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2009,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2010,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2011,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2012,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,5.0,7.0,7.0,5.0,7.0,7.0,5.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2013,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2014,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,6.0,8.0,5.0,6.0,7.0,5.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2015,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2016,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2017,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2018,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2019,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2020,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2022,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2023,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0
2024,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0
2025,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [182]:
# df = df[
#     (df.year==2025)
#     # (df.round_num>=21)
# ]
# df

In [183]:
df.Home.unique()

array(['Rams', 'Broncos', 'Warriors', 'Tigers', 'Eels', 'Sharks', 'Steelers', 'Bears', 'Bulldogs', 'Dragons', 'Knights', 'Rabbitohs', 'Roosters', 'Raiders', 'Magpies', 'Panthers', 'Chargers', 'Cowboys', 'Storm', 'Sea Eagles', 'Wests Tigers', 'Eagles', 'Titans', 'Dolphins'], dtype=object)

In [203]:
duckdb.sql(
    '''
    CREATE OR REPLACE TABLE win_loss_draw AS 
        WITH base AS (
            SELECT
                year,
                round_num,
                Home AS home_team,
                Home_Score AS home_score,
                Away AS away_team,
                Away_Score AS away_score
            FROM 
                df
        )
    
        SELECT
            year,
            round_num,
            home_team AS team,
            home_score AS pts_for,
            away_score AS pts_against,
            IF(home_score > away_score, 1, 0) AS win,
            IF(home_score = away_score, 1, 0) AS draw,
            IF(home_score < away_score, 1, 0) AS loss
        FROM
            base
    
        UNION ALL
    
        SELECT
            year,
            round_num,
            away_team AS team,
            away_score AS pts_for,
            home_score AS pts_against,
            IF(away_score > home_score, 1, 0) AS win,
            IF(away_score = home_score, 1, 0) AS draw,
            IF(away_score < home_score, 1, 0) AS loss
        FROM
            base
    '''
)

In [208]:
duckdb.sql(
    '''
    -- will include all teams even in the finals rounds
    -- but won't matter as it won't join to anything in the train_df

    CREATE OR REPLACE TABLE spine_team AS
    
        WITH year_team AS (
            SELECT DISTINCT
                year,
                team
            FROM win_loss_draw
        ),
    
        year_round AS (
            SELECT DISTINCT
                year,
                round_num
            FROM win_loss_draw
        )
    
        SELECT
            yr.year,
            yr.round_num,
            yt.team
        FROM
            year_round AS yr
        LEFT JOIN
            year_team AS yt
        ON
            yr.year = yt.year
    '''
)
spine_df = duckdb.sql('select * from spine_team').df()
spine_df.groupby(['year', 'round_num']).team.nunique().unstack()

round_num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1998,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
1999,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,NaN
2000,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,NaN
2001,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,NaN
2002,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2003,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2004,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2005,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2006,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2007,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2008,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2009,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2010,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2011,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2012,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2013,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2014,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2015,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2016,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2017,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2018,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2019,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2020,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2022,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2023,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0
2024,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0
2025,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [188]:
spine_df.isnull().sum()

year         0
round_num    0
team         0
dtype: int64

In [213]:
duckdb.sql(
    '''
    CREATE OR REPLACE TABLE win_loss_draw_full AS
        SELECT
            s.year,
            s.round_num,
            s.team,
            IF(w.team IS NULL, 1, 0) AS bye,
            COALESCE(w.pts_for, 0) AS pts_for,
            COALESCE(w.pts_against, 0) AS pts_against,
            COALESCE(w.win, 0) AS win,
            COALESCE(w.draw, 0) AS draw,
            COALESCE(w.loss, 0) AS loss
        FROM
            spine_team AS s
        LEFT JOIN
            win_loss_draw AS w
        ON
            s.year = w.year
            AND s.round_num = w.round_num
            AND s.team = w.team
    '''
)
wld_full_df = duckdb.sql('select * from win_loss_draw_full').df()
wld_full_df.groupby(['year', 'round_num']).team.nunique().unstack()
wld_full_df.groupby(['year', 'round_num']).bye.sum().unstack()
wld_full_df.groupby(['year', 'team']).bye.sum().unstack()

round_num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1998,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
1999,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,NaN
2000,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,NaN
2001,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,14.0,NaN
2002,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2003,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2004,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2005,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2006,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,NaN
2007,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2008,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2009,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2010,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2011,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2012,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2013,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2014,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2015,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2016,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2017,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN
2018,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2019,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2020,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2022,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,NaN
2023,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0
2024,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0
2025,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

round_num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,16.0,16.0,16.0,16.0,16.0,18.0
1999,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,13.0,13.0,15.0,NaN
2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,10.0,12.0,NaN
2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,10.0,12.0,NaN
2002,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,11.0,11.0,13.0,NaN
2003,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,11.0,11.0,13.0,NaN
2004,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,11.0,11.0,13.0,NaN
2005,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,11.0,11.0,13.0,NaN
2006,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,11.0,11.0,13.0,NaN
2007,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN
2008,0.0,0.0,0.0,0.0,0.0,0.0,4.0,6.0,4.0,0.0,6.0,0.0,0.0,6.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,2.0,2.0,6.0,2.0,2.0,6.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2013,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2.0,0.0,8.0,2.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,4.0,0.0,6.0,4.0,2.0,6.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2.0,0.0,8.0,2.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2.0,0.0,8.0,2.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2.0,0.0,8.0,2.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN
2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN
2019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN
2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN
2022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,12.0,12.0,14.0,NaN,NaN
2023,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,13.0,13.0,15.0
2024,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.0,13.0,13.0,15.0
2025,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,7.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

team,Bears,Broncos,Bulldogs,Chargers,Cowboys,Dolphins,Dragons,Eagles,Eels,Knights,Magpies,Panthers,Rabbitohs,Raiders,Rams,Roosters,Sea Eagles,Sharks,Steelers,Storm,Tigers,Titans,Warriors,Wests Tigers
year,,,,,,,,,,,,,,,,,,,,,,,,
1998,5.0,3.0,2.0,7.0,7.0,NaN,6.0,NaN,4.0,5.0,7.0,7.0,7.0,5.0,7.0,4.0,6.0,7.0,7.0,4.0,7.0,NaN,7.0,NaN
1999,6.0,5.0,4.0,NaN,6.0,NaN,2.0,NaN,4.0,5.0,6.0,6.0,6.0,6.0,NaN,4.0,6.0,4.0,NaN,2.0,6.0,NaN,6.0,NaN
2000,NaN,1.0,4.0,NaN,4.0,NaN,4.0,4.0,1.0,2.0,NaN,2.0,NaN,2.0,NaN,0.0,NaN,3.0,NaN,3.0,NaN,NaN,4.0,4.0
2001,NaN,1.0,2.0,NaN,4.0,NaN,2.0,4.0,1.0,1.0,NaN,4.0,NaN,4.0,NaN,3.0,NaN,1.0,NaN,4.0,NaN,NaN,3.0,4.0
2002,NaN,4.0,6.0,NaN,6.0,NaN,4.0,6.0,5.0,4.0,NaN,6.0,6.0,5.0,NaN,2.0,NaN,3.0,NaN,6.0,NaN,NaN,3.0,6.0
2003,NaN,5.0,3.0,NaN,6.0,NaN,6.0,NaN,6.0,5.0,NaN,3.0,6.0,4.0,NaN,3.0,6.0,6.0,NaN,4.0,NaN,NaN,3.0,6.0
2004,NaN,4.0,2.0,NaN,3.0,NaN,5.0,NaN,6.0,6.0,NaN,4.0,6.0,5.0,NaN,3.0,6.0,6.0,NaN,4.0,NaN,NaN,6.0,6.0
2005,NaN,4.0,6.0,NaN,2.0,NaN,4.0,NaN,4.0,6.0,NaN,6.0,6.0,6.0,NaN,6.0,5.0,5.0,NaN,4.0,NaN,NaN,6.0,2.0
2006,NaN,2.0,4.0,NaN,6.0,NaN,3.0,NaN,5.0,4.0,NaN,6.0,6.0,5.0,NaN,6.0,4.0,6.0,NaN,3.0,NaN,NaN,6.0,6.0
2007,NaN,4.0,3.0,NaN,2.0,NaN,5.0,NaN,2.0,5.0,NaN,5.0,4.0,5.0,NaN,5.0,2.0,5.0,NaN,2.0,NaN,5.0,3.0,5.0
2008,NaN,4.0,6.0,NaN,6.0,NaN,5.0,NaN,6.0,6.0,NaN,6.0,6.0,5.0,NaN,4.0,3.0,4.0,NaN,2.0,NaN,6.0,3.0,6.0
2009,NaN,3.0,4.0,NaN,6.0,NaN,4.0,NaN,2.0,5.0,NaN,6.0,6.0,6.0,NaN,6.0,5.0,6.0,NaN,3.0,NaN,4.0,6.0,6.0
2010,NaN,6.0,6.0,NaN,6.0,NaN,3.0,NaN,6.0,6.0,NaN,4.0,6.0,4.0,NaN,2.0,5.0,6.0,NaN,6.0,NaN,4.0,5.0,3.0
2011,NaN,3.0,6.0,NaN,5.0,NaN,4.0,NaN,6.0,5.0,NaN,6.0,6.0,6.0,NaN,6.0,3.0,6.0,NaN,4.0,NaN,6.0,2.0,4.0
2012,NaN,5.0,3.0,NaN,4.0,NaN,6.0,NaN,6.0,6.0,NaN,6.0,3.0,4.0,NaN,6.0,3.0,5.0,NaN,3.0,NaN,6.0,6.0,6.0
2013,NaN,6.0,5.0,NaN,5.0,NaN,6.0,NaN,6.0,3.0,NaN,6.0,4.0,6.0,NaN,3.0,2.0,4.0,NaN,4.0,NaN,6.0,6.0,6.0
2014,NaN,5.0,2.0,NaN,4.0,NaN,6.0,NaN,6.0,6.0,NaN,4.0,3.0,6.0,NaN,3.0,4.0,6.0,NaN,5.0,NaN,6.0,6.0,6.0
2015,NaN,3.0,4.0,NaN,2.0,NaN,5.0,NaN,6.0,6.0,NaN,6.0,5.0,6.0,NaN,3.0,6.0,4.0,NaN,4.0,NaN,6.0,6.0,6.0
2016,NaN,4.0,5.0,NaN,3.0,NaN,6.0,NaN,6.0,6.0,NaN,4.0,6.0,3.0,NaN,6.0,6.0,3.0,NaN,3.0,NaN,5.0,6.0,6.0
2017,NaN,3.0,6.0,NaN,2.0,NaN,6.0,NaN,4.0,6.0,NaN,4.0,6.0,6.0,NaN,4.0,5.0,5.0,NaN,3.0,NaN,6.0,6.0,6.0
2018,NaN,4.0,5.0,NaN,5.0,NaN,3.0,NaN,5.0,5.0,NaN,3.0,2.0,5.0,NaN,2.0,5.0,2.0,NaN,2.0,NaN,5.0,4.0,5.0
2019,NaN,4.0,5.0,NaN,5.0,NaN,5.0,NaN,3.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,3.0,4.0,NaN,2.0,NaN,5.0,5.0,5.0
2020,NaN,4.0,4.0,NaN,4.0,NaN,4.0,NaN,2.0,3.0,NaN,1.0,1.0,1.0,NaN,2.0,4.0,3.0,NaN,1.0,NaN,4.0,4.0,4.0
2021,NaN,5.0,5.0,NaN,5.0,NaN,5.0,NaN,3.0,4.0,NaN,1.0,2.0,5.0,NaN,3.0,2.0,5.0,NaN,3.0,NaN,4.0,5.0,5.0
2022,NaN,5.0,5.0,NaN,3.0,NaN,5.0,NaN,1.0,5.0,NaN,2.0,2.0,3.0,NaN,4.0,5.0,3.0,NaN,4.0,NaN,5.0,5.0,5.0
2023,NaN,4.0,7.0,NaN,7.0,7.0,7.0,NaN,7.0,5.0,NaN,4.0,7.0,6.0,NaN,5.0,7.0,6.0,NaN,4.0,NaN,7.0,4.0,7.0
2024,NaN,7.0,6.0,NaN,5.0,7.0,7.0,NaN,7.0,6.0,NaN,4.0,7.0,7.0,NaN,4.0,5.0,4.0,NaN,4.0,NaN,7.0,7.0,7.0
2025,NaN,3.0,3.0,NaN,2.0,3.0,3.0,NaN,3.0,3.0,NaN,3.0,2.0,2.0,NaN,3.0,3.0,2.0,NaN,3.0,NaN,3.0,3.0,2.0

In [218]:
duckdb.sql(
    '''
    CREATE OR REPLACE TABLE features_team AS
        WITH ladder AS (
            SELECT
                year,
                round_num,
                team,
                COALESCE(SUM(bye) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS byes,
                COALESCE(SUM(win) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS wins,
                COALESCE(SUM(draw) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS draws,
                COALESCE(SUM(loss) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS losses,
                COALESCE(SUM(pts_for) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS pts_for,
                COALESCE(SUM(pts_against) OVER (
                    PARTITION BY
                        year,
                        team
                    ORDER BY
                        round_num
                ), 0) AS pts_against
            FROM win_loss_draw_full
        ),
    
        ladder_final AS (
            SELECT
                year,
                round_num,
                team,
                CAST(round_num - byes AS INT) AS played,
                CAST(byes AS INT) AS byes,
                CAST(wins AS INT) AS wins,
                CAST(draws AS INT) AS draws,
                CAST(losses AS INT) AS losses,
                CAST(2*wins + 2*byes + 1*draws AS INT) AS points,
                CAST(pts_for AS INT) AS pts_for,
                CAST(pts_against AS INT) AS pts_against,
                CAST(pts_for - pts_against AS INT) AS pts_diff
            FROM ladder
        )
    
        SELECT
            *,
            RANK() OVER (
                PARTITION BY
                    year,
                    round_num
                ORDER BY
                    points DESC,
                    pts_diff DESC
            ) AS ladder_position
        FROM ladder_final
    '''
)

In [220]:
feature_df = duckdb.sql('select * from features_team').df()
feature_df[feature_df.round_num==21].sort_values('ladder_position').reset_index(drop=True)

,year,round_num,team,played,byes,wins,draws,losses,points,pts_for,pts_against,pts_diff,ladder_position
0,1998,21,Broncos,21,0,15,1,5,31,634,286,348,1
1,2014,21,Sea Eagles,19,2,14,0,5,32,429,287,142,1
2,2001,21,Eels,21,0,15,2,4,32,700,326,374,1
3,2005,21,Broncos,19,2,15,0,4,34,529,372,157,1
4,2022,21,Panthers,20,1,18,0,2,38,556,242,314,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,1999,21,Magpies,19,2,3,0,16,10,225,694,-469,17
443,1998,21,Rams,21,0,7,0,14,14,363,513,-150,17
444,1998,21,Rabbitohs,21,0,4,0,17,8,291,490,-199,18
445,1998,21,Chargers,21,0,4,0,17,8,249,581,-332,19
446,1998,21,Magpies,21,0,4,0,17,8,347,694,-347,20

In [227]:
duckdb.sql(
    '''
    CREATE OR REPLACE TABLE labels AS
        SELECT
            year,
            round_num,
            Home AS home_team,
            Away AS away_team,
            CAST(Home_Score - Away_Score AS INT) AS margin,
            IF(Home_Score > Away_Score, 1, 0) AS home_win
        FROM
            df 
    '''
)
label_df = duckdb.sql('select * from labels').df()
label_df.groupby('year').round_num.value_counts().unstack()

round_num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1998,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0
1999,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2000,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2001,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2002,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2003,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2004,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2005,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2006,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,4.0,2.0,2.0,1.0,NaN
2007,8.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2008,8.0,8.0,8.0,8.0,8.0,8.0,6.0,5.0,6.0,8.0,5.0,8.0,8.0,5.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2009,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2010,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2011,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2012,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,5.0,7.0,7.0,5.0,7.0,7.0,5.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2013,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2014,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,6.0,8.0,5.0,6.0,7.0,5.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2015,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2016,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2017,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,4.0,7.0,8.0,4.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN
2018,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2019,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2020,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2022,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0,NaN,NaN
2023,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0
2024,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,2.0,2.0,1.0
2025,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,5.0,7.0,8.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [228]:
duckdb.sql(
    '''
    CREATE OR REPLACE TABLE train AS
        SELECT
            labels.* EXCLUDE(home_win, margin),
            -- coalesce for round 1
            COALESCE(home.ladder_position, 0) AS ladder_position_home,
            COALESCE(away.ladder_position, 0) AS ladder_position_away,
            COALESCE(-1 * (home.ladder_position - away.ladder_position), 0) AS home_ladder_pos_diff,
            labels.home_win
        FROM
            labels AS labels
        LEFT JOIN
            features_team AS home
        ON
            labels.year = home.year
            AND labels.round_num - 1 = home.round_num
            AND labels.home_team = home.team
        LEFT JOIN
            features_team AS away
        ON
            labels.year = away.year
            AND labels.round_num - 1 = away.round_num
            AND labels.away_team = away.team
    '''
)
train_df = duckdb.sql('select * from train').df()
train_df[train_df.round_num==22]
train_df

,year,round_num,home_team,away_team,ladder_position_home,ladder_position_away,home_ladder_pos_diff,home_win
164,1998,22,Storm,Sharks,2,9,7,1
165,1998,22,Knights,Chargers,3,19,16,1
166,1998,22,Bears,Tigers,5,13,8,1
167,1998,22,Dragons,Bulldogs,8,11,3,0
168,1998,22,Steelers,Roosters,10,6,-4,0
...,...,...,...,...,...,...,...,...
5245,2017,22,Dragons,Rabbitohs,8,14,6,0
5246,2017,22,Panthers,Wests Tigers,9,15,6,1
5247,2017,22,Titans,Broncos,12,4,-8,0
5248,2017,22,Bulldogs,Eels,13,6,-7,0
5249,2017,22,Knights,Warriors,16,11,-5,1

,year,round_num,home_team,away_team,ladder_position_home,ladder_position_away,home_ladder_pos_diff,home_win
0,2010,24,Knights,Broncos,13,9,-4,1
1,2010,24,Cowboys,Bulldogs,16,14,-2,0
2,2010,25,Wests Tigers,Storm,3,5,2,1
3,2010,25,Roosters,Sea Eagles,7,6,-1,1
4,2010,25,Warriors,Broncos,8,9,1,1
...,...,...,...,...,...,...,...,...
5562,2015,1,Sharks,Raiders,0,0,0,0
5563,2017,1,Sharks,Broncos,0,0,0,0
5564,2019,1,Roosters,Rabbitohs,0,0,0,0
5565,2020,1,Raiders,Titans,0,0,0,1
5566,2020,1,Rabbitohs,Sharks,0,0,0,1

In [229]:
train_df.to_csv('train_df.csv', index=False)